import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import AuthNav from '../components/AuthNav';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="p-4 border-b flex justify-between items-center">
          <h1 className="text-xl font-bold">FastBreak Dashboard</h1>
          <AuthNav />
        </header>
        <main className="p-4">{children}</main>
      </body>
    </html>
  );
}
