CREATE TABLE players (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  position TEXT,
  traded_midseason BOOLEAN DEFAULT FALSE,
  gp INT,
  gs INT,
  min FLOAT,
  pts FLOAT,
  or FLOAT,
  dr FLOAT,
  reb FLOAT,
  ast FLOAT,
  stl FLOAT,
  blk FLOAT,
  to FLOAT,
  pf FLOAT,
  ast_to FLOAT,
  fgm FLOAT,
  fga FLOAT,
  fg_pct FLOAT,
  three_pm FLOAT,
  three_pa FLOAT,
  three_pct FLOAT,
  ftm FLOAT,
  fta FLOAT,
  ft_pct FLOAT,
  two_pm FLOAT,
  two_pa FLOAT,
  two_pct FLOAT,
  sc_eff FLOAT,
  sh_eff FLOAT
);
